---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: opxhub/dcind
inputs:
- name: src
outputs:
- name: dist
params:
- DIST: jessie
run:
  path: bash
  args:
  - -ec
  - |
    source /docker-lib.sh; start_docker
    pushd src
    ./docker_build.sh
    version="$(git rev-parse --short HEAD)-$DIST"
    popd
    docker images
    docker save opxhub/build:$DIST -o dist/image.tar
    echo $version >dist/version

